<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $alert['title'] ?? 'Alert Notification' }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }

        .alert-container {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            margin: 20px 0;
        }

        .alert-success {
            background-color: #d4edda;
            border-color: #c3e6cb;
            color: #155724;
        }

        .alert-error {
            background-color: #f8d7da;
            border-color: #f5c6cb;
            color: #721c24;
        }

        .alert-warning {
            background-color: #fff3cd;
            border-color: #ffeaa7;
            color: #856404;
        }

        .alert-info {
            background-color: #d1ecf1;
            border-color: #bee5eb;
            color: #0c5460;
        }

        .alert-header {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .alert-message {
            font-size: 16px;
            margin-bottom: 15px;
        }

        .alert-meta {
            font-size: 14px;
            color: #666;
            border-top: 1px solid #eee;
            padding-top: 10px;
            margin-top: 15px;
        }

        .alert-actions {
            margin-top: 15px;
        }

        .btn {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 4px;
            margin-right: 10px;
        }

        .btn:hover {
            background-color: #0056b3;
        }

        .btn-secondary {
            background-color: #6c757d;
        }

        .btn-secondary:hover {
            background-color: #545b62;
        }

        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>

<body>
    <div class="alert-container alert-{{ $alert['type'] ?? 'info' }}">
        <div class="alert-header">
            {{ $alert['title'] ?? ucfirst($alert['type'] ?? 'Alert') }}
        </div>

        <div class="alert-message">
            {{ $alert['message'] }}
        </div>

        @if (isset($alert['context']) && $alert['context'])
            <div class="alert-context">
                <strong>Context:</strong> {{ $alert['context'] }}
            </div>
        @endif

        @if (isset($alert['field']) && $alert['field'])
            <div class="alert-field">
                <strong>Field:</strong> {{ $alert['field'] }}
            </div>
        @endif

        @if (isset($alert['form']) && $alert['form'])
            <div class="alert-form">
                <strong>Form:</strong> {{ $alert['form'] }}
            </div>
        @endif

        <div class="alert-meta">
            <strong>Type:</strong> {{ ucfirst($alert['type'] ?? 'info') }}<br>
            <strong>Priority:</strong> {{ $alert['priority'] ?? 'Normal' }}<br>
            <strong>Timestamp:</strong>
            {{ $alert['created_at'] ? \Carbon\Carbon::parse($alert['created_at'])->format('Y-m-d H:i:s') : now()->format('Y-m-d H:i:s') }}
        </div>

        @if (isset($alert['actions']) && is_array($alert['actions']))
            <div class="alert-actions">
                @foreach ($alert['actions'] as $action)
                    <a href="{{ $action['url'] }}" class="btn {{ $action['class'] ?? '' }}">
                        {{ $action['text'] }}
                    </a>
                @endforeach
            </div>
        @endif
    </div>

    <div class="footer">
        <p>This alert was generated by Laravel Alert system.</p>
        <p>If you no longer wish to receive these notifications, please contact your system administrator.</p>
    </div>
</body>

</html>
