<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Multiple Alerts Notification</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }

        .alerts-container {
            margin: 20px 0;
        }

        .alert-item {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 15px;
            margin: 10px 0;
        }

        .alert-success {
            background-color: #d4edda;
            border-color: #c3e6cb;
            color: #155724;
        }

        .alert-error {
            background-color: #f8d7da;
            border-color: #f5c6cb;
            color: #721c24;
        }

        .alert-warning {
            background-color: #fff3cd;
            border-color: #ffeaa7;
            color: #856404;
        }

        .alert-info {
            background-color: #d1ecf1;
            border-color: #bee5eb;
            color: #0c5460;
        }

        .alert-header {
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 8px;
        }

        .alert-message {
            font-size: 14px;
            margin-bottom: 10px;
        }

        .alert-meta {
            font-size: 12px;
            color: #666;
            border-top: 1px solid #eee;
            padding-top: 8px;
            margin-top: 10px;
        }

        .summary {
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 20px;
        }

        .summary h3 {
            margin-top: 0;
            color: #495057;
        }

        .summary-stats {
            display: flex;
            justify-content: space-around;
            margin-top: 10px;
        }

        .stat-item {
            text-align: center;
        }

        .stat-number {
            font-size: 24px;
            font-weight: bold;
            color: #007bff;
        }

        .stat-label {
            font-size: 12px;
            color: #666;
        }

        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>

<body>
    <div class="summary">
        <h3>Alert Summary</h3>
        <p>You have received {{ count($alerts) }} new alerts:</p>

        <div class="summary-stats">
            @php
                $stats = [
                    'success' => 0,
                    'error' => 0,
                    'warning' => 0,
                    'info' => 0,
                ];
                foreach ($alerts as $alert) {
                    $type = $alert['type'] ?? 'info';
                    if (isset($stats[$type])) {
                        $stats[$type]++;
                    }
                }
            @endphp

            @foreach ($stats as $type => $count)
                @if ($count > 0)
                    <div class="stat-item">
                        <div class="stat-number">{{ $count }}</div>
                        <div class="stat-label">{{ ucfirst($type) }}</div>
                    </div>
                @endif
            @endforeach
        </div>
    </div>

    <div class="alerts-container">
        @foreach ($alerts as $alert)
            <div class="alert-item alert-{{ $alert['type'] ?? 'info' }}">
                <div class="alert-header">
                    {{ $alert['title'] ?? ucfirst($alert['type'] ?? 'Alert') }}
                </div>

                <div class="alert-message">
                    {{ $alert['message'] }}
                </div>

                @if (isset($alert['context']) && $alert['context'])
                    <div class="alert-context">
                        <strong>Context:</strong> {{ $alert['context'] }}
                    </div>
                @endif

                <div class="alert-meta">
                    <strong>Type:</strong> {{ ucfirst($alert['type'] ?? 'info') }} |
                    <strong>Priority:</strong> {{ $alert['priority'] ?? 'Normal' }} |
                    <strong>Time:</strong>
                    {{ $alert['created_at'] ? \Carbon\Carbon::parse($alert['created_at'])->format('H:i:s') : now()->format('H:i:s') }}
                </div>
            </div>
        @endforeach
    </div>

    <div class="footer">
        <p>This summary was generated by Laravel Alert system.</p>
        <p>If you no longer wish to receive these notifications, please contact your system administrator.</p>
    </div>
</body>

</html>
